# Definisanje resursa - Tabela za punjače
  Resources:
    ChargersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chargers-local
        AttributeDefinitions:
          - AttributeName: charger_id
            AttributeType: S
        KeySchema:
          - AttributeName: charger_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
