Resources:
  ChargersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chargerId
          AttributeType: S
        - AttributeName: town
          AttributeType: S
      KeySchema:
        - AttributeName: chargerId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TownIndex
          KeySchema:
            - AttributeName: town
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: local-matf-ev-charger-frontend
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
